site_name: !ENV [SITE_NAME, "makedocsio-github-test-bash"]
site_url: !ENV [SITE_URL, "https://github.com/motowilliams/makedocsio-github-test-bash"]
site_dir: !ENV [SITE_DIR, "site"]
docs_dir: !ENV [DOCS_DIR, "content"]
repo_url: !ENV [REPO_URL, "https://github.com/motowilliams/makedocsio-github-test-bash"]
theme: material

plugins:
  - search
  - macros:
      modules: [mkdocs-macros-file-include]
nav:
  - "Home": "index.md"
